### ISSUE TITLE
svg的部分无法使用css或latex中\color{}设置颜色

### ISSUE THREAD

**Issue by had0ngzhu** [rojer95/katex-mini#1]
由于将svg放置在img内，无法通过css的color或fill属性控制svg的颜色，同时\color{}也使用css控制颜色，导致两种方法均无法设置svg颜色，可以使用css的filter强制转换，或在img中src的svg标签内嵌入fill='color'
![A96072344A37562E5BB34A3D25F54B2D](https://user-images.githubusercontent.com/67865626/178419008-b866db3e-87c2-4f29-949c-a35326cf11b3.jpg)

**Comment by rojer95** [comment]
#2
