### ISSUE TITLE
如何添加宏包呢

### ISSUE THREAD

**Issue by lipeilin7570** [rojer95/katex-mini#10]
如何添加mechem.js使其支持化学公式的显示呢

**Comment by rojer95** [comment]
把这个插件的代码下载下来，
然后直接在 小程序的app.js进行 import 即可

![image](https://github.com/user-attachments/assets/9d5020d1-3f65-4e40-b983-9d22567e4747)

![image](https://github.com/user-attachments/assets/9736b0c5-5ded-4468-ba7e-f90b11ed1617)
