### ISSUE TITLE
How to set up to return html instead of nodes

### ISSUE THREAD

**Issue by Libpzzz** [rojer95/katex-mini#12]
Are there any other configuration items? I want to display html instead of the default nodes

**Comment by rojer95** [comment]
If you want to display HTML, you can directly use Katex's [renderoString](https://katex.org/docs/api#server-side-rendering-or-rendering-to-a-string) method for parsing
but html is not user-friendly in mini programs

**Comment by Libpzzz** [comment]
Thank you for your feedback. Initially, I used Katex's renderoString method to display the tags, but I found that some of the tags in the WeChat mini program seemed incompatible and could not display the style I wanted. Now, I can manually convert the nodes to HTML using parse to meet my needs
