### ISSUE TITLE
使用之后如何控制richtext的样式？

### ISSUE THREAD

**Issue by birdol** [rojer95/katex-mini#4]
前端使用了colorui的界面。 目前渲染是正常的。 但是wxml调试器里看不到选然后的richtext，放到view里，view就不见了。如何控制样式？ 比如text-align:center

**Comment by birdol** [comment]
另外还有个问题，https://lf26-cdn-tos.bytecdntp.com/  这个cdn可以换成自己的吗？ 需要上传/配置哪些文件？

**Comment by birdol** [comment]
凑，是我自己弄错了。 样式控制没问题。目前就这个cdn有点疑问，想换掉，可以内置到小程序里或者用自己的服务器吗？

**Comment by rojer95** [comment]
> 凑，是我自己弄错了。 样式控制没问题。目前就这个cdn有点疑问，想换掉，可以内置到小程序里或者用自己的服务器吗？

这个主要的latex用到的的字体，可以换成自己的url

**Comment by birdol** [comment]
能在外面控制KateX的几个设置参数吗？ 比如那个 displayMode，inline我想要的。虽然现在也够用了。

再次感谢作者的辛苦劳动。

**Comment by rojer95** [comment]
> 

https://github.com/rojer95/katex-mini/blob/2b8c2015c0dd9114477509ff0f2c0d33cf9181b4/src/index.ts#L169

option
