### ISSUE TITLE
rich-text \n <br> 都不能换行

### ISSUE THREAD

**Issue by xiemy1214** [rojer95/katex-mini#5]
小程序集成了该库, 转换效果挺好的 , 但是现在遇到一个问题.  

_index.wxml_

> <view class="container">
>   ...
>   <scroll-view class="scroll-view" scroll-x="true">
>     <rich-text  nodes="{{nodes}}" class='latex-container' bindlongpress="copyContent" data-text="{{nodes}}" selectable='true' 
> data-type="2"></rich-text>
>   </scroll-view>
>   ...
> </view>

_index.wxss ->_

> ...
> .latex-container {
>   word-break:break-all;
>   width: 100%;
>   height: 100%;
>   padding: 6px;
>   color: #323232;
>   font-size: 12px;
> }
> ...

_index.js ->_

> import parse from '@rojer/katex-mini'
> 
> Page{
> 
> 	data: {
> 		nodes: [],
> 		latex: `9. 用简便方法计算下面各题.
> 		3.8 \\times 1.45+0.38 \\times 4.2+0.038 \\times 13"
> 		\\frac{1}{2}+\\frac{1}{4}+\\frac{1}{8}+\\ldots \\ldots+\\frac{1}{128}`,
> 	},
> 
> 	onShow() {
> 	  this.renderLatex()
> 	},
> 
> 	renderLatex: function () {
> 	  var content = this.data.latex;
> 	  console.log(content)
> 	  if (content.includes('\\(') && content.includes('\\)')) {
> 		content = content.replace(/\\\(/g, '').replace(/\\\)/g, '');
> 	  }
> 	  
> 	  if (content.includes('\\[') && content.includes('\\]')) {
> 		content = content.replace(/\\\[/g, '').replace(/\\\]/g, '');
> 	  }
> 	  
> 	  if (content.includes('\\\\')) {
> 		content = content.replace(/\\\\/g, '').replace(/\n/g, '');
> 	  }
>   
> 	  ...
> 	}
> }

运行效果如下:
![temp](https://github.com/rojer95/katex-mini/assets/82264481/98adee73-6f57-4001-89ca-2c9cdbc2e840)

请问大佬有解决方法吗?
非常感谢 !

**Comment by rojer95** [comment]
尝试一下 \newline 用于换行

**Comment by xiemy1214** [comment]
谢谢! 我刚才在KaTex项目中搜了一下换行, newline 确实可以解决换行. 
还遇到的问题就是
没法靠左对齐跟文本复制,  
请问有什么好的方法吗?

![temp2](https://github.com/rojer95/katex-mini/assets/82264481/c307ea03-bb4d-4aa3-8824-93f517e1b6ed)

**Comment by rojer95** [comment]
左对齐确实没有很好的办法。我目前有涉及题目的项目是混合编排的
就是题干中非latex部分是用View来写的，然后把latex的RichNode放进去 inline
