### ISSUE TITLE
请问可以输出html格式的结果吗，目前我看输出的是json的

### ISSUE THREAD

**Issue by Xuzhangzheng** [rojer95/katex-mini#7]

**Comment by Xuzhangzheng** [comment]
好的谢谢

**Comment by rojer95** [comment]
![image](https://github.com/rojer95/katex-mini/assets/20662049/06189866-7de3-4231-b037-47ad3b6e49ea)

我这边试了是下角标的，你试试这个Demo

**Comment by Xuzhangzheng** [comment]
十分感谢，已经解决了，tks
