### ISSUE TITLE
请问是不支持$$..$$这种定界符包裹的公式吗？

### ISSUE THREAD

**Issue by hnxylc8818** [rojer95/katex-mini#8]
之前H5使用katex的renderMathInElement方法可以支持$${\\dfrac{6}{8}}+{\\dfrac{1}{11}}$$ 这种格式的公式，试了一下这个小程序的好像不支持，渲染错误，请教一下大佬这个是不支持吗？
![image](https://github.com/rojer95/katex-mini/assets/14075517/d68b28d3-d27f-4631-8cdc-8c97dd73b83a)

**Comment by rojer95** [comment]
你好，renderMathInElement是katex的扩展库，
因为小程序的特殊性，这个在无法支持，需要您自己写正则提取出来做解析
